using System.Collections.Immutable;
using Windvale.Bytecode;

namespace Windvale.Compiler;

internal enum Wirˉoperation
{
    I32ˉconstant,
    I64ˉconstant,
    U8ˉconstant,
    U32ˉconstant,
    U64ˉconstant,
    Boolˉconstant,
    Textˉconstant,
    Bytesˉconstant,
    Loadˉlocal,
    Storeˉlocal,
    Dataˉlength,
    Dataˉloadˉi32,
    Bytesˉlength,
    Bytesˉslice,
    Bytesˉreadˉu8,
    Bytesˉreadˉu16ˉlittle,
    Bytesˉreadˉu32ˉlittle,
    Bytesˉreadˉi32ˉlittle,
    Bytesˉreadˉu64ˉlittle,
    Recordˉcreate,
    Recordˉfield,
    Enumˉconstant,
    Enumˉequal,
    Enumˉnotˉequal,
    Enumˉname,
    Variantˉcreate,
    Variantˉisˉcase,
    Variantˉpayload,
    Builderˉcreate,
    Builderˉpush,
    Builderˉfreeze,
    Sequenceˉlength,
    Sequenceˉelement,
    I32ˉformat,
    I64ˉformat,
    U8ˉformat,
    U32ˉformat,
    U64ˉformat,
    U32ˉfromˉu8,
    Textˉconcat,
    Textˉutf8ˉisˉvalid,
    Textˉfromˉutf8,
    Textˉquote,
    Bytesˉconcat,
    Bytesˉfromˉu8,
    Bytesˉfromˉu16ˉlittle,
    Bytesˉfromˉu32ˉlittle,
    Bytesˉfromˉi32ˉlittle,
    Bytesˉfromˉu64ˉlittle,
    Bytesˉsha256ˉhex,
    Textˉtoˉutf8,
    I32ˉadd,
    I32ˉsubtract,
    I32ˉmultiply,
    I32ˉnegate,
    I64ˉadd,
    I64ˉsubtract,
    I64ˉmultiply,
    I64ˉnegate,
    U32ˉadd,
    U32ˉsubtract,
    U32ˉmultiply,
    U64ˉadd,
    U64ˉsubtract,
    U64ˉmultiply,
    I32ˉequal,
    I32ˉnotˉequal,
    I32ˉless,
    I32ˉlessˉequal,
    I32ˉgreater,
    I32ˉgreaterˉequal,
    I64ˉequal,
    I64ˉnotˉequal,
    I64ˉless,
    I64ˉlessˉequal,
    I64ˉgreater,
    I64ˉgreaterˉequal,
    Boolˉequal,
    Boolˉnotˉequal,
    Boolˉnot,
    U32ˉequal,
    U32ˉnotˉequal,
    U32ˉless,
    U32ˉlessˉequal,
    U32ˉgreater,
    U32ˉgreaterˉequal,
    U64ˉequal,
    U64ˉnotˉequal,
    U64ˉless,
    U64ˉlessˉequal,
    U64ˉgreater,
    U64ˉgreaterˉequal,
    U8ˉequal,
    U8ˉnotˉequal,
    I32ˉdivide,
    I32ˉremainder,
    U32ˉdivide,
    U32ˉremainder,
    I64ˉdivide,
    I64ˉremainder,
    U64ˉdivide,
    U64ˉremainder,
    U8ˉbitwiseˉand,
    U8ˉbitwiseˉor,
    U8ˉbitwiseˉxor,
    U8ˉbitwiseˉnot,
    U8ˉshiftˉleft,
    U8ˉshiftˉright,
    U32ˉbitwiseˉand,
    U32ˉbitwiseˉor,
    U32ˉbitwiseˉxor,
    U32ˉbitwiseˉnot,
    U32ˉshiftˉleft,
    U32ˉshiftˉright,
    U64ˉbitwiseˉand,
    U64ˉbitwiseˉor,
    U64ˉbitwiseˉxor,
    U64ˉbitwiseˉnot,
    U64ˉshiftˉleft,
    U64ˉshiftˉright,
    Textˉequal,
    Textˉnotˉequal,
    Bytesˉequal,
    Bytesˉnotˉequal,
    Callˉfunction,
    Callˉcapability,
    Boolˉphi,
}

internal sealed record Wirˉinstruction(
    Wirˉoperation Operation,
    int? Result,
    ImmutableArray<int> Operands,
    int Integerˉoperand = 0,
    uint Unsignedˉintegerˉoperand = 0,
    uint Secondˉunsignedˉintegerˉoperand = 0,
    long Wideˉintegerˉoperand = 0,
    ulong Unsignedˉwideˉintegerˉoperand = 0,
    string? Nameˉoperand = null);

internal abstract record Wirˉterminator;

internal sealed record Wirˉjump(int Targetˉblock) : Wirˉterminator;

internal sealed record Wirˉbranch(
    int Condition,
    int Trueˉblock,
    int Falseˉblock)
    : Wirˉterminator;

internal sealed record Wirˉreturn(int? Value) : Wirˉterminator;

internal sealed record Wirˉblock(
    int Id,
    ImmutableArray<Wirˉinstruction> Instructions,
    Wirˉterminator Terminator);

internal sealed record Wirˉfunction(
    string Name,
    ImmutableArray<Valueˉshape> Parameterˉtypes,
    Valueˉshape Returnˉtype,
    ImmutableArray<Valueˉshape> Userˉlocalˉtypes,
    ImmutableArray<Valueˉshape> Temporaryˉtypes,
    ImmutableArray<Wirˉblock> Blocks,
    bool Isˉexported);

internal sealed record Wirˉmodule(
    string Name,
    Moduleˉprofile Profile,
    Moduleˉmetadata? Metadata,
    ImmutableArray<Capabilityˉdeclaration> Capabilities,
    ImmutableArray<Dataˉdeclaration> Data,
    ImmutableArray<Nominalˉtypeˉdeclaration> Types,
    ImmutableArray<Wirˉfunction> Functions);
