<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>windvale</AssemblyName>
    <Description>Windvale Seed command-line tool.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../Assembler/Reference/Windvale.Assembler.csproj" />
    <ProjectReference Include="../../Compiler/Native/Windvale.NativeCompiler.csproj" />
    <ProjectReference Include="../../Compiler/Reference/Windvale.Compiler.csproj" />
    <ProjectReference Include="../../Linker/Reference/Windvale.Linker.csproj" />
    <ProjectReference Include="../../Object-Model/Windvale.ObjectModel/Windvale.ObjectModel.csproj" />
    <ProjectReference Include="../../Runtime/Windvale.Bytecode/Windvale.Bytecode.csproj" />
    <ProjectReference Include="../../Runtime/Windvale.Runtime/Windvale.Runtime.csproj" />
    <ProjectReference Include="../Windvale.Project/Windvale.Project.csproj" />
  </ItemGroup>
</Project>
