export const SUPPORT_TIERS = Object.freeze([
    {
        key: "spark",
        name: "Spark",
        amount: "$20",
        note: "A first spark",
        icon: "flare",
        accent: "cyan",
        image: new URL("./assets/support/spark.jpg", import.meta.url).href,
        description: "Helps cover the AI compute and tools behind an active development session.",
        checkoutUrl: "https://buy.stripe.com/fZu8wI2vi8hFeB8e9G1sQ00",
    },
    {
        key: "builder",
        name: "Builder",
        amount: "$50",
        note: "Build with us",
        icon: "construction",
        accent: "green",
        image: new URL("./assets/support/builder.jpg", import.meta.url).href,
        description: "Supports continued work across the compiler, runtime, playground, and documentation.",
        checkoutUrl: "https://buy.stripe.com/6oU28k0nacxV50y7Li1sQ01",
    },
    {
        key: "accelerator",
        name: "Accelerator",
        amount: "$100",
        note: "Strong momentum",
        icon: "speed",
        accent: "blue",
        image: new URL("./assets/support/accelerator.jpg", import.meta.url).href,
        description: "Helps fund deeper implementation, verification, and cross-platform testing.",
        checkoutUrl: "https://buy.stripe.com/00wcMYb1O41pgJg9Tq1sQ02",
    },
    {
        key: "champion",
        name: "Champion",
        amount: "$500",
        note: "Major support",
        icon: "workspace_premium",
        accent: "violet",
        image: new URL("./assets/support/champion.jpg", import.meta.url).href,
        description: "Sustains a substantial block of focused development and testing work.",
        checkoutUrl: "https://buy.stripe.com/6oU3cob1OfK71Om4z61sQ03",
    },
    {
        key: "cornerstone",
        name: "Cornerstone Supporter",
        amount: "$1,000",
        note: "Long-term impact",
        icon: "foundation",
        accent: "amber",
        image: new URL("./assets/support/cornerstone.jpg", import.meta.url).href,
        description: "Makes a major contribution to Windvale's long-term community development.",
        checkoutUrl: "https://buy.stripe.com/8x214g1redBZeB87Li1sQ04",
    },
    {
        key: "any",
        name: "Choose Your Support",
        amount: "Any amount",
        note: "Every amount helps",
        icon: "volunteer_activism",
        accent: "green",
        image: new URL("./assets/support/any-amount.jpg", import.meta.url).href,
        description: "Choose the one-time amount that feels right for you. Every contribution matters.",
        checkoutUrl: "https://buy.stripe.com/aFa28k5Hu7dB64CfdK1sQ05",
    },
]);

export const SUPPORT_CURRENCY = "USD";
