import type { Localizationˉpack } from '../../../../Libraries/Web/Framework/Localization/Localization';

const English: Readonly<Record<string, string>> = Object.freeze({
  'frame.product': 'WVDB Workbench',
  'frame.context': 'Development / Customers',
  'frame.preview': 'SYNTHETIC PREVIEW',
  'frame.search': 'Search commands…  Ctrl+K',
  'frame.explorer': 'Toggle server explorer',
  'frame.assistant': 'Toggle AI assistant',
  'frame.theme': 'Switch color theme',
  'frame.locale': 'Passer au français',
  'frame.install': 'Install',
  'frame.settings': 'Settings',
  'ribbon.collapse': 'Expand or collapse the ribbon',
  'ribbon.home': 'Home',
  'ribbon.query': 'Query',
  'ribbon.data': 'Data',
  'ribbon.schema': 'Schema',
  'ribbon.operations': 'Operations',
  'ribbon.ai': 'AI',
  'group.query': 'Query',
  'group.view': 'View',
  'group.connection': 'Connection',
  'group.results': 'Results',
  'group.records': 'Records',
  'group.schema': 'Schema',
  'group.operations': 'Operations',
  'group.assistant': 'Assistant',
  'command.new_query': 'New query',
  'command.validate': 'Validate',
  'command.execute': 'Execute',
  'command.explorer': 'Explorer',
  'command.console': 'Console',
  'command.assistant': 'Assistant',
  'command.connect': 'Connect',
  'command.disconnect': 'Disconnect',
  'command.export': 'Export',
  'command.browse': 'Browse rows',
  'command.new_record': 'New record',
  'command.save': 'Save',
  'command.collection': 'Collection',
  'command.index': 'Index',
  'command.backup': 'Backup',
  'command.restore': 'Restore',
  'command.ask': 'Ask about query',
  'command.explain': 'Explain plan',
  'explorer.title': 'Servers',
  'explorer.filter': 'Filter servers and collections',
  'explorer.add': 'Add connection',
  'explorer.expand_all': 'Expand or collapse all',
  'explorer.saved_profiles': 'Saved profiles',
  'explorer.no_profiles': 'No locally saved profiles',
  'explorer.local': 'Local WVDB Service',
  'explorer.synthetic': 'preview connection',
  'explorer.database': 'Development',
  'explorer.collections': 'Collections',
  'explorer.customers': 'Customers',
  'explorer.orders': 'Orders',
  'explorer.agent_runs': 'Agent-Runs',
  'explorer.indexes': 'Indexes',
  'explorer.operations': 'Operations',
  'work.overview': 'Overview',
  'work.query': 'Query 1',
  'work.customers': 'Customers',
  'work.query_title': 'Bounded typed query',
  'work.query_subtitle': 'Draft against Development / Customers',
  'work.preview_only': 'LOCAL VALIDATION ONLY',
  'work.draft': 'Draft',
  'work.valid': 'Valid preview',
  'work.parameters': 'Parameters',
  'work.status_parameter': '$status',
  'work.status_value': 'active',
  'work.query_bounds': 'WVQI 1 preview bounds',
  'work.bound_collection': 'One collection and schema',
  'work.bound_predicates': 'Up to 32 AND predicates',
  'work.bound_orders': 'Up to 8 order terms',
  'work.bound_limit': 'Row limit 1–500',
  'work.result_preview': 'Result preview',
  'work.synthetic_rows': '3 synthetic rows · no service request',
  'work.column_id': 'Customer ID',
  'work.column_name': 'Display name',
  'work.column_region': 'Region',
  'work.column_status': 'Status',
  'work.active': 'active',
  'work.overview_title': 'Development database',
  'work.overview_copy': 'A representative workspace for the evolving WVDB contracts.',
  'work.card_collections': 'Collections',
  'work.card_indexes': 'Indexes',
  'work.card_generation': 'Preview generation',
  'work.customer_title': 'Customers',
  'work.customer_copy': 'Synthetic records for layout and interaction work.',
  'toolbar.new': 'New', 'toolbar.validate': 'Validate', 'toolbar.format': 'Format',
  'toolbar.copy': 'Copy', 'toolbar.execute': 'Execute', 'toolbar.local_context': 'Local draft · no live service',
  'assistant.title': 'Windvale Assistant',
  'assistant.preview': 'LOCAL PREVIEW · NO MODEL CALL',
  'assistant.context': 'Context: current query and selected collection. No database content leaves this browser.',
  'assistant.placeholder': 'Ask about this query…',
  'assistant.send': 'Send',
  'assistant.collapse': 'Collapse assistant',
  'assistant.new_chat': 'New local chat', 'assistant.query_context': 'Current query',
  'assistant.schema_context': 'Selected schema', 'assistant.session_only': 'Session only · no model call',
  'assistant.suggestion_validate': 'Check the current query bounds',
  'assistant.suggestion_bounds': 'Explain the WVQI preview limits',
  'assistant.suggestion_index': 'What index might this query need?',
  'assistant.welcome': 'I can help shape a bounded WVQI query, inspect its declared limits, and prepare future administration steps. This preview does not contact WVDB or a model provider.',
  'assistant.deterministic_reply': 'For this preview I can only give a deterministic local response. The query targets one collection, uses one equality predicate, one order term, and a limit of 50—inside the current WVQI 1 bounds.',
  'assistant.local_meta': 'Generated locally · synthetic guidance',
  'console.title': 'Console',
  'console.activity': 'Activity',
  'console.problems': 'Problems',
  'console.clear': 'Clear',
  'console.copy': 'Copy',
  'console.no_problems': 'No local problems detected.',
  'log.shell_ready': 'Workbench shell initialized.',
  'log.preview_loaded': 'Loaded synthetic Development catalog (3 collections).',
  'log.no_service': 'No WVDB service is configured; execution and mutations are unavailable.',
  'log.query_opened': 'Opened a local query draft. No database operation was dispatched.',
  'log.query_validated': 'Local WVQI preview validation passed: 1 collection, 1 predicate, 1 order, limit 50.',
  'log.assistant_local': 'Produced a deterministic local assistant reply; no model call was made.',
  'log.assistant_reset': 'Started a new session-only assistant chat.',
  'log.query_formatted': 'Formatted the query draft locally.',
  'log.profile_saved': 'Saved a connection profile in this browser. No connection was attempted.',
  'log.profile_deleted': 'Deleted a locally saved connection profile.',
  'palette.title': 'Command palette', 'palette.placeholder': 'Type a command…', 'palette.empty': 'No matching commands',
  'palette.local_command': 'Runs locally in this preview', 'palette.saved_profile': 'Create a locally saved future-server profile',
  'palette.layout_command': 'Changes the workbench layout', 'palette.preference': 'Updates a local preference', 'palette.ribbon': 'Toggle ribbon',
  'dialog.connection_title': 'Add connection profile', 'dialog.connection_edit': 'Edit connection profile',
  'dialog.connection_copy': 'Prepare a future WVDB service address. Saving does not connect.',
  'dialog.name': 'Display name', 'dialog.endpoint': 'Service endpoint', 'dialog.database': 'Default database',
  'dialog.profile_note': 'Stored only in this browser. Credentials and database contents are never stored here.',
  'dialog.cancel': 'Cancel', 'dialog.save_profile': 'Save profile', 'dialog.delete': 'Delete',
  'dialog.error_name': 'Enter a display name of 1–64 characters.',
  'dialog.error_endpoint': 'Use HTTPS, or HTTP only for localhost/loopback. Usernames, passwords, and fragments are not allowed.',
  'dialog.error_database': 'Enter a database name of 1–64 characters.', 'dialog.error_storage': 'The profile could not be saved, or the limit of eight profiles was reached.',
  'settings.title': 'Workbench settings', 'settings.copy': 'Choose local appearance and language preferences.',
  'settings.theme': 'Theme', 'settings.dark': 'Dark', 'settings.light': 'Light', 'settings.language': 'Language',
  'settings.storage': 'These settings and panel sizes are stored locally. No server authority or credential is retained.',
  'settings.reset_layout': 'Reset panel layout', 'settings.apply': 'Apply',
  'status.server': 'Local WVDB Service',
  'status.database': 'Development',
  'status.mode': 'Synthetic / read-only',
  'status.rows': '3 rows previewed',
  'status.connection': 'No live connection',
  'status.console': 'Console'
});

const French: Readonly<Record<string, string>> = Object.freeze({
  'frame.product': 'Atelier WVDB',
  'frame.context': 'Développement / Clients',
  'frame.preview': 'APERÇU SYNTHÉTIQUE',
  'frame.search': 'Rechercher les commandes…  Ctrl+K',
  'frame.explorer': 'Afficher l’explorateur de serveurs',
  'frame.assistant': 'Afficher l’assistant IA',
  'frame.theme': 'Changer le thème',
  'frame.locale': 'Switch to English',
  'frame.install': 'Installer',
  'frame.settings': 'Paramètres', 'ribbon.collapse': 'Développer ou réduire le ruban',
  'ribbon.home': 'Accueil', 'ribbon.query': 'Requête', 'ribbon.data': 'Données',
  'ribbon.schema': 'Schéma', 'ribbon.operations': 'Opérations', 'ribbon.ai': 'IA',
  'group.query': 'Requête', 'group.view': 'Affichage', 'group.connection': 'Connexion',
  'group.results': 'Résultats', 'group.records': 'Enregistrements', 'group.schema': 'Schéma',
  'group.operations': 'Opérations', 'group.assistant': 'Assistant',
  'command.new_query': 'Nouvelle requête', 'command.validate': 'Valider',
  'command.execute': 'Exécuter', 'command.explorer': 'Explorateur', 'command.console': 'Console',
  'command.assistant': 'Assistant', 'command.connect': 'Connecter', 'command.disconnect': 'Déconnecter',
  'command.export': 'Exporter', 'command.browse': 'Parcourir', 'command.new_record': 'Nouvel élément',
  'command.save': 'Enregistrer', 'command.collection': 'Collection', 'command.index': 'Index',
  'command.backup': 'Sauvegarder', 'command.restore': 'Restaurer',
  'command.ask': 'Analyser la requête', 'command.explain': 'Expliquer le plan',
  'explorer.title': 'Serveurs', 'explorer.filter': 'Filtrer les serveurs et collections',
  'explorer.add': 'Ajouter une connexion', 'explorer.local': 'Service WVDB local',
  'explorer.expand_all': 'Tout développer ou réduire', 'explorer.saved_profiles': 'Profils enregistrés',
  'explorer.no_profiles': 'Aucun profil local enregistré',
  'explorer.synthetic': 'connexion d’aperçu', 'explorer.database': 'Développement',
  'explorer.collections': 'Collections', 'explorer.customers': 'Clients',
  'explorer.orders': 'Commandes', 'explorer.agent_runs': 'Exécutions-agent',
  'explorer.indexes': 'Index', 'explorer.operations': 'Opérations',
  'work.overview': 'Vue d’ensemble', 'work.query': 'Requête 1', 'work.customers': 'Clients',
  'work.query_title': 'Requête typée bornée', 'work.query_subtitle': 'Brouillon sur Développement / Clients',
  'work.preview_only': 'VALIDATION LOCALE SEULEMENT', 'work.draft': 'Brouillon',
  'work.valid': 'Aperçu valide', 'work.parameters': 'Paramètres',
  'work.status_parameter': '$status', 'work.status_value': 'active',
  'work.query_bounds': 'Limites de l’aperçu WVQI 1', 'work.bound_collection': 'Une collection et un schéma',
  'work.bound_predicates': 'Jusqu’à 32 prédicats ET', 'work.bound_orders': 'Jusqu’à 8 termes de tri',
  'work.bound_limit': 'Limite de 1 à 500 lignes', 'work.result_preview': 'Aperçu des résultats',
  'work.synthetic_rows': '3 lignes synthétiques · aucune requête au service',
  'work.column_id': 'ID client', 'work.column_name': 'Nom affiché', 'work.column_region': 'Région',
  'work.column_status': 'Statut', 'work.active': 'actif',
  'work.overview_title': 'Base Développement',
  'work.overview_copy': 'Un espace représentatif pour les contrats WVDB en évolution.',
  'work.card_collections': 'Collections', 'work.card_indexes': 'Index',
  'work.card_generation': 'Génération d’aperçu', 'work.customer_title': 'Clients',
  'work.customer_copy': 'Enregistrements synthétiques pour le travail d’interface.',
  'toolbar.new': 'Nouveau', 'toolbar.validate': 'Valider', 'toolbar.format': 'Formater',
  'toolbar.copy': 'Copier', 'toolbar.execute': 'Exécuter', 'toolbar.local_context': 'Brouillon local · aucun service actif',
  'assistant.title': 'Assistant Windvale', 'assistant.preview': 'APERÇU LOCAL · AUCUN APPEL AU MODÈLE',
  'assistant.context': 'Contexte : requête actuelle et collection choisie. Aucune donnée ne quitte ce navigateur.',
  'assistant.placeholder': 'Demander au sujet de cette requête…', 'assistant.send': 'Envoyer',
  'assistant.collapse': 'Réduire l’assistant',
  'assistant.new_chat': 'Nouvelle discussion locale', 'assistant.query_context': 'Requête actuelle',
  'assistant.schema_context': 'Schéma choisi', 'assistant.session_only': 'Session seulement · aucun appel au modèle',
  'assistant.suggestion_validate': 'Vérifier les limites de la requête',
  'assistant.suggestion_bounds': 'Expliquer les limites WVQI',
  'assistant.suggestion_index': 'Quel index pourrait aider cette requête?',
  'assistant.welcome': 'Je peux aider à préparer une requête WVQI bornée et à vérifier ses limites. Cet aperçu ne contacte ni WVDB ni un fournisseur de modèle.',
  'assistant.deterministic_reply': 'Dans cet aperçu, ma réponse est locale et déterministe. La requête vise une collection avec un prédicat, un tri et une limite de 50 — dans les limites WVQI 1.',
  'assistant.local_meta': 'Généré localement · conseils synthétiques',
  'console.title': 'Console', 'console.activity': 'Activité', 'console.problems': 'Problèmes',
  'console.clear': 'Effacer', 'console.copy': 'Copier',
  'console.no_problems': 'Aucun problème local détecté.',
  'log.shell_ready': 'Coque de l’atelier initialisée.',
  'log.preview_loaded': 'Catalogue synthétique Développement chargé (3 collections).',
  'log.no_service': 'Aucun service WVDB configuré; l’exécution et les mutations sont indisponibles.',
  'log.query_opened': 'Brouillon local ouvert. Aucune opération de base de données envoyée.',
  'log.query_validated': 'Validation locale WVQI réussie : 1 collection, 1 prédicat, 1 tri, limite 50.',
  'log.assistant_local': 'Réponse locale déterministe produite; aucun appel au modèle.',
  'log.assistant_reset': 'Nouvelle discussion locale démarrée.', 'log.query_formatted': 'Brouillon formaté localement.',
  'log.profile_saved': 'Profil enregistré dans ce navigateur. Aucune connexion tentée.',
  'log.profile_deleted': 'Profil local supprimé.',
  'palette.title': 'Palette de commandes', 'palette.placeholder': 'Saisir une commande…', 'palette.empty': 'Aucune commande correspondante',
  'palette.local_command': 'S’exécute localement dans cet aperçu', 'palette.saved_profile': 'Créer un profil local pour un futur serveur',
  'palette.layout_command': 'Modifie la disposition', 'palette.preference': 'Met à jour une préférence locale', 'palette.ribbon': 'Afficher le ruban',
  'dialog.connection_title': 'Ajouter un profil de connexion', 'dialog.connection_edit': 'Modifier le profil',
  'dialog.connection_copy': 'Préparer l’adresse d’un futur service WVDB. Enregistrer ne connecte pas.',
  'dialog.name': 'Nom affiché', 'dialog.endpoint': 'Adresse du service', 'dialog.database': 'Base par défaut',
  'dialog.profile_note': 'Stocké seulement dans ce navigateur. Aucun identifiant ni contenu de base n’est conservé.',
  'dialog.cancel': 'Annuler', 'dialog.save_profile': 'Enregistrer le profil', 'dialog.delete': 'Supprimer',
  'dialog.error_name': 'Saisir un nom de 1 à 64 caractères.',
  'dialog.error_endpoint': 'Utiliser HTTPS, ou HTTP seulement pour localhost. Identifiants et fragments interdits.',
  'dialog.error_database': 'Saisir un nom de base de 1 à 64 caractères.', 'dialog.error_storage': 'Impossible d’enregistrer le profil, ou limite de huit atteinte.',
  'settings.title': 'Paramètres de l’atelier', 'settings.copy': 'Choisir les préférences locales d’apparence et de langue.',
  'settings.theme': 'Thème', 'settings.dark': 'Sombre', 'settings.light': 'Clair', 'settings.language': 'Langue',
  'settings.storage': 'Ces paramètres et tailles sont stockés localement. Aucune autorité ni identifiant serveur n’est retenu.',
  'settings.reset_layout': 'Réinitialiser la disposition', 'settings.apply': 'Appliquer',
  'status.server': 'Service WVDB local', 'status.database': 'Développement',
  'status.mode': 'Synthétique / lecture seule', 'status.rows': '3 lignes affichées',
  'status.connection': 'Aucune connexion active', 'status.console': 'Console'
});

export const Wvdbˉworkbenchˉlocalizationˉpacks: readonly Localizationˉpack[] = Object.freeze([
  { Locale: 'en', Scope: 'wvdb', Messages: English },
  { Locale: 'fr', Scope: 'wvdb', Messages: French }
]);
